Some changes

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -7,35 +7,37 @@ on:
       - feature/add-ci
 
 jobs:
-  deploy:
+  build-ios:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/setup-java@v2
-        with:
-          distribution: 'zulu'
-          java-version: '11'
-      - name: Android NDK toolchain Setup
-        uses: nttld/setup-ndk@v1
-        with:
-          ndk-version: r21e
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           channel: 'dev'
           cache-key: flutter-mac
           architecture: x64
-      - name: Install Flutter
-        run: |
-          flutter config --enable-web --enable-ios --enable-android
-          flutter pub get
-      - name: Check format
-        run: flutter format --set-exit-if-changed . || { echo -e "${RED}Invalid format" ; exit 1; }
-      - name: Run Linter
-        run: flutter analyze . || { echo -e "${RED}Linter error" ; exit 1; }
-      - name: Build Web
-        run: cd example && flutter build web
-      - name: Build Android
-        run: cd example && flutter build apk --debug
       - name: Build Ios
-        run: cd example && flutter build ipa
+        run: cd example && flutter build ipa --no-codesign
+  build-android-web:
+    runs-on: ubuntu-18.04
+    steps:
+        - uses: actions/checkout@v3
+        - uses: actions/setup-java@v2
+          with:
+            distribution: 'zulu'
+            java-version: '11'
+        - name: Setup Flutter
+          uses: subosito/flutter-action@v2
+          with:
+            channel: 'dev'
+        - name: Get dependencies
+          run: flutter pub get
+        - name: Check format
+          run: flutter format --set-exit-if-changed . || { echo -e "${RED}Invalid format" ; exit 1; }
+        - name: Run Linter
+          run: flutter analyze . || { echo -e "${RED}Linter error" ; exit 1; }
+        - name: Build Web
+          run: cd example && flutter build web
+        - name: Build Android
+          run: cd example && flutter build apk --debug
